# Generated by Django 5.0.3 on 2024-07-03 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 14, 42, 14, 578351)),
        ),
    ]
