# Generated by Django 5.0.3 on 2024-07-07 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 7, 10, 23, 32, 786140)),
        ),
    ]
