# Generated by Django 5.0.3 on 2024-07-07 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 7, 10, 27, 0, 527721, tzinfo=datetime.timezone.utc)),
        ),
    ]
