# Generated by Django 5.0.3 on 2024-07-07 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 7, 10, 27, 42, 547513, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 7, 10, 27, 42, 549640, tzinfo=datetime.timezone.utc)),
        ),
    ]
