# Generated by Django 5.0.3 on 2024-06-29 13:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name_of_final_product', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='product_name',
            new_name='product',
        ),
        migrations.AddField(
            model_name='composition',
            name='composition_name',
            field=models.CharField(default='name', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='bialko_ogolne',
            field=models.DecimalField(decimal_places=1, default=12, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='wapń',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='wilgotnosc',
            field=models.DecimalField(decimal_places=1, default=12, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='ProductionElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('delivery_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.delivery')),
                ('production_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.production')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('composition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.composition')),
            ],
        ),
        migrations.AddField(
            model_name='production',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.recipe'),
        ),
        migrations.CreateModel(
            name='RecipeElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product')),
                ('recipe_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.recipe')),
            ],
        ),
    ]
