# Generated by Django 5.0.3 on 2024-07-07 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_alter_delivery_date_alter_production_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
