# Generated by Django 5.0.3 on 2024-07-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_alter_production_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='wapń',
            new_name='wapn',
        ),
    ]
