# Generated by Django 5.0.3 on 2024-08-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_rename_wapń_product_wapn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
    ]
