# Generated by Django 5.0.3 on 2024-08-16 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_remove_delivery_price_currency_alter_delivery_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
