# Generated by Django 5.0.3 on 2024-08-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_alter_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='number_of_positions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
